name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, macos-11.0, ubuntu-latest, ubuntu-20.04, windows-latest]
  
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
